baseURL: www.adrianglinqvist.se/
languageCode: en-us
title: Adrian Glinqvist's Porfolio
theme: "PaperMod"


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Adrian Glinqvist's Portfolio
  description: "My portfolio of projects and ideas"
  keywords: [Blog, Portfolio, Ideas, PaperMod]
  author: Adrian Glinqvist
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

  socialIcons: # optional
    - name: "<platform>"
      url: "<link>"
    - name: "<platform 2>"
      url: "<link2>"

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/icons/heart_red.svg"
    favicon16x16: "/icons/heart_red.svg"
    favicon32x32: "/icons/heart_red.svg"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "\U0001F3E0"
    icon: #/icons/home.svg
    iconHeight: 25

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hello \U0001F44B"
    subtitle: "I'm Adrian Glinqvist, an AI Consultant and bussiness developer fokusing on the ROI of AI solutions. Based in Stockholm, Sweden."
    imageUrl: "/img/ag600-removebg-preview.png"
    imageWidth: 240
    imageHeight: 240
    imageTitle: my image
    buttons:
      - name: Blog
        url: posts
      #- name: Tags
        #url: tags
      - name: Projects
        url: projects

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/adrian-glinqvist/"
    - name: github
      url: "https://github.com/AdrianG-AIBC"
    - name: twitter
      url: "https://twitter.com/"
    - name: email
      url: "mailto:adrian.glinqvist@gmail.com"
    #- name: cv
    #  url: " "

#  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"
#    bing:  
#      SiteVerificationTag: "XYZabc"
#    yandex:
#      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false  # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  #editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html

#outputs:
#    home:
#        - HTML
#        - RSS
#        - JSON # is necessary

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: categories
      name: blog
      url: /posts/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: projects
      name: projects
      url: /projects/
      weight: 30
    - identifier: resume
      name: resume
    #  url: https://example.org
      weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai